require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Admin::CompanyDetailsController do

  # This should return the minimal set of attributes required to create a valid
  # Admin::CompanyDetail. As you add validations to Admin::CompanyDetail, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Admin::CompanyDetailsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all admin_company_details as @admin_company_details" do
      company_detail = Admin::CompanyDetail.create! valid_attributes
      get :index, {}, valid_session
      assigns(:admin_company_details).should eq([company_detail])
    end
  end

  describe "GET show" do
    it "assigns the requested company_detail as @company_detail" do
      company_detail = Admin::CompanyDetail.create! valid_attributes
      get :show, {:id => company_detail.to_param}, valid_session
      assigns(:company_detail).should eq(company_detail)
    end
  end

  describe "GET new" do
    it "assigns a new company_detail as @company_detail" do
      get :new, {}, valid_session
      assigns(:company_detail).should be_a_new(Admin::CompanyDetail)
    end
  end

  describe "GET edit" do
    it "assigns the requested company_detail as @company_detail" do
      company_detail = Admin::CompanyDetail.create! valid_attributes
      get :edit, {:id => company_detail.to_param}, valid_session
      assigns(:company_detail).should eq(company_detail)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Admin::CompanyDetail" do
        expect {
          post :create, {:company_detail => valid_attributes}, valid_session
        }.to change(Admin::CompanyDetail, :count).by(1)
      end

      it "assigns a newly created company_detail as @company_detail" do
        post :create, {:company_detail => valid_attributes}, valid_session
        assigns(:company_detail).should be_a(Admin::CompanyDetail)
        assigns(:company_detail).should be_persisted
      end

      it "redirects to the created company_detail" do
        post :create, {:company_detail => valid_attributes}, valid_session
        response.should redirect_to(Admin::CompanyDetail.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved company_detail as @company_detail" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::CompanyDetail.any_instance.stub(:save).and_return(false)
        post :create, {:company_detail => {}}, valid_session
        assigns(:company_detail).should be_a_new(Admin::CompanyDetail)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::CompanyDetail.any_instance.stub(:save).and_return(false)
        post :create, {:company_detail => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested company_detail" do
        company_detail = Admin::CompanyDetail.create! valid_attributes
        # Assuming there are no other admin_company_details in the database, this
        # specifies that the Admin::CompanyDetail created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Admin::CompanyDetail.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => company_detail.to_param, :company_detail => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested company_detail as @company_detail" do
        company_detail = Admin::CompanyDetail.create! valid_attributes
        put :update, {:id => company_detail.to_param, :company_detail => valid_attributes}, valid_session
        assigns(:company_detail).should eq(company_detail)
      end

      it "redirects to the company_detail" do
        company_detail = Admin::CompanyDetail.create! valid_attributes
        put :update, {:id => company_detail.to_param, :company_detail => valid_attributes}, valid_session
        response.should redirect_to(company_detail)
      end
    end

    describe "with invalid params" do
      it "assigns the company_detail as @company_detail" do
        company_detail = Admin::CompanyDetail.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::CompanyDetail.any_instance.stub(:save).and_return(false)
        put :update, {:id => company_detail.to_param, :company_detail => {}}, valid_session
        assigns(:company_detail).should eq(company_detail)
      end

      it "re-renders the 'edit' template" do
        company_detail = Admin::CompanyDetail.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::CompanyDetail.any_instance.stub(:save).and_return(false)
        put :update, {:id => company_detail.to_param, :company_detail => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested company_detail" do
      company_detail = Admin::CompanyDetail.create! valid_attributes
      expect {
        delete :destroy, {:id => company_detail.to_param}, valid_session
      }.to change(Admin::CompanyDetail, :count).by(-1)
    end

    it "redirects to the admin_company_details list" do
      company_detail = Admin::CompanyDetail.create! valid_attributes
      delete :destroy, {:id => company_detail.to_param}, valid_session
      response.should redirect_to(admin_company_details_url)
    end
  end

end
