require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Admin::ContactDetailsController do

  # This should return the minimal set of attributes required to create a valid
  # Admin::ContactDetail. As you add validations to Admin::ContactDetail, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Admin::ContactDetailsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all admin_contact_details as @admin_contact_details" do
      contact_detail = Admin::ContactDetail.create! valid_attributes
      get :index, {}, valid_session
      assigns(:admin_contact_details).should eq([contact_detail])
    end
  end

  describe "GET show" do
    it "assigns the requested contact_detail as @contact_detail" do
      contact_detail = Admin::ContactDetail.create! valid_attributes
      get :show, {:id => contact_detail.to_param}, valid_session
      assigns(:contact_detail).should eq(contact_detail)
    end
  end

  describe "GET new" do
    it "assigns a new contact_detail as @contact_detail" do
      get :new, {}, valid_session
      assigns(:contact_detail).should be_a_new(Admin::ContactDetail)
    end
  end

  describe "GET edit" do
    it "assigns the requested contact_detail as @contact_detail" do
      contact_detail = Admin::ContactDetail.create! valid_attributes
      get :edit, {:id => contact_detail.to_param}, valid_session
      assigns(:contact_detail).should eq(contact_detail)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Admin::ContactDetail" do
        expect {
          post :create, {:contact_detail => valid_attributes}, valid_session
        }.to change(Admin::ContactDetail, :count).by(1)
      end

      it "assigns a newly created contact_detail as @contact_detail" do
        post :create, {:contact_detail => valid_attributes}, valid_session
        assigns(:contact_detail).should be_a(Admin::ContactDetail)
        assigns(:contact_detail).should be_persisted
      end

      it "redirects to the created contact_detail" do
        post :create, {:contact_detail => valid_attributes}, valid_session
        response.should redirect_to(Admin::ContactDetail.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved contact_detail as @contact_detail" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::ContactDetail.any_instance.stub(:save).and_return(false)
        post :create, {:contact_detail => {}}, valid_session
        assigns(:contact_detail).should be_a_new(Admin::ContactDetail)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::ContactDetail.any_instance.stub(:save).and_return(false)
        post :create, {:contact_detail => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested contact_detail" do
        contact_detail = Admin::ContactDetail.create! valid_attributes
        # Assuming there are no other admin_contact_details in the database, this
        # specifies that the Admin::ContactDetail created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Admin::ContactDetail.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => contact_detail.to_param, :contact_detail => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested contact_detail as @contact_detail" do
        contact_detail = Admin::ContactDetail.create! valid_attributes
        put :update, {:id => contact_detail.to_param, :contact_detail => valid_attributes}, valid_session
        assigns(:contact_detail).should eq(contact_detail)
      end

      it "redirects to the contact_detail" do
        contact_detail = Admin::ContactDetail.create! valid_attributes
        put :update, {:id => contact_detail.to_param, :contact_detail => valid_attributes}, valid_session
        response.should redirect_to(contact_detail)
      end
    end

    describe "with invalid params" do
      it "assigns the contact_detail as @contact_detail" do
        contact_detail = Admin::ContactDetail.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::ContactDetail.any_instance.stub(:save).and_return(false)
        put :update, {:id => contact_detail.to_param, :contact_detail => {}}, valid_session
        assigns(:contact_detail).should eq(contact_detail)
      end

      it "re-renders the 'edit' template" do
        contact_detail = Admin::ContactDetail.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::ContactDetail.any_instance.stub(:save).and_return(false)
        put :update, {:id => contact_detail.to_param, :contact_detail => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested contact_detail" do
      contact_detail = Admin::ContactDetail.create! valid_attributes
      expect {
        delete :destroy, {:id => contact_detail.to_param}, valid_session
      }.to change(Admin::ContactDetail, :count).by(-1)
    end

    it "redirects to the admin_contact_details list" do
      contact_detail = Admin::ContactDetail.create! valid_attributes
      delete :destroy, {:id => contact_detail.to_param}, valid_session
      response.should redirect_to(admin_contact_details_url)
    end
  end

end
