require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Admin::ExpenseTypesController do

  # This should return the minimal set of attributes required to create a valid
  # Admin::ExpenseType. As you add validations to Admin::ExpenseType, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Admin::ExpenseTypesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all admin_expense_types as @admin_expense_types" do
      expense_type = Admin::ExpenseType.create! valid_attributes
      get :index, {}, valid_session
      assigns(:admin_expense_types).should eq([expense_type])
    end
  end

  describe "GET show" do
    it "assigns the requested expense_type as @expense_type" do
      expense_type = Admin::ExpenseType.create! valid_attributes
      get :show, {:id => expense_type.to_param}, valid_session
      assigns(:expense_type).should eq(expense_type)
    end
  end

  describe "GET new" do
    it "assigns a new expense_type as @expense_type" do
      get :new, {}, valid_session
      assigns(:expense_type).should be_a_new(Admin::ExpenseType)
    end
  end

  describe "GET edit" do
    it "assigns the requested expense_type as @expense_type" do
      expense_type = Admin::ExpenseType.create! valid_attributes
      get :edit, {:id => expense_type.to_param}, valid_session
      assigns(:expense_type).should eq(expense_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Admin::ExpenseType" do
        expect {
          post :create, {:expense_type => valid_attributes}, valid_session
        }.to change(Admin::ExpenseType, :count).by(1)
      end

      it "assigns a newly created expense_type as @expense_type" do
        post :create, {:expense_type => valid_attributes}, valid_session
        assigns(:expense_type).should be_a(Admin::ExpenseType)
        assigns(:expense_type).should be_persisted
      end

      it "redirects to the created expense_type" do
        post :create, {:expense_type => valid_attributes}, valid_session
        response.should redirect_to(Admin::ExpenseType.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved expense_type as @expense_type" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::ExpenseType.any_instance.stub(:save).and_return(false)
        post :create, {:expense_type => {}}, valid_session
        assigns(:expense_type).should be_a_new(Admin::ExpenseType)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::ExpenseType.any_instance.stub(:save).and_return(false)
        post :create, {:expense_type => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested expense_type" do
        expense_type = Admin::ExpenseType.create! valid_attributes
        # Assuming there are no other admin_expense_types in the database, this
        # specifies that the Admin::ExpenseType created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Admin::ExpenseType.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => expense_type.to_param, :expense_type => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested expense_type as @expense_type" do
        expense_type = Admin::ExpenseType.create! valid_attributes
        put :update, {:id => expense_type.to_param, :expense_type => valid_attributes}, valid_session
        assigns(:expense_type).should eq(expense_type)
      end

      it "redirects to the expense_type" do
        expense_type = Admin::ExpenseType.create! valid_attributes
        put :update, {:id => expense_type.to_param, :expense_type => valid_attributes}, valid_session
        response.should redirect_to(expense_type)
      end
    end

    describe "with invalid params" do
      it "assigns the expense_type as @expense_type" do
        expense_type = Admin::ExpenseType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::ExpenseType.any_instance.stub(:save).and_return(false)
        put :update, {:id => expense_type.to_param, :expense_type => {}}, valid_session
        assigns(:expense_type).should eq(expense_type)
      end

      it "re-renders the 'edit' template" do
        expense_type = Admin::ExpenseType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::ExpenseType.any_instance.stub(:save).and_return(false)
        put :update, {:id => expense_type.to_param, :expense_type => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested expense_type" do
      expense_type = Admin::ExpenseType.create! valid_attributes
      expect {
        delete :destroy, {:id => expense_type.to_param}, valid_session
      }.to change(Admin::ExpenseType, :count).by(-1)
    end

    it "redirects to the admin_expense_types list" do
      expense_type = Admin::ExpenseType.create! valid_attributes
      delete :destroy, {:id => expense_type.to_param}, valid_session
      response.should redirect_to(admin_expense_types_url)
    end
  end

end
